backend:
    name: git-gateway
    branch: master
media_folder: static/assets
public_folder: assets
collections:
    -
        name: caseStudies
        label: Case Studies
        folder: src/pages/case-studies
        create: true
        fields:
            - {name: category, label: Category, default: Case Study, widget: hidden}
            - {name: date, label: Date, widget: date}
            - {name: title, label: Title}
            - {name: intro, label: Introduction, widget: text}
            - {name: mainImage, label: Main Image, widget: image, default: /src/images/mitso-default.png}
            - {name: body, label: Body, widget: markdown}
            - {name: imageBlock, label: Image Block, widget: list, fields: [{label: image, name: Image, widget: image}]}
            - {name: testimonial, label: Testimonial, widget: text}
    -
        name: thoughts
        label: Thoughts
        folder: src/pages/thoughts
        create: true
        fields:
            - {name: category, label: Category, default: Blog, widget: hidden}
            - {name: date, label: Date, widget: date}
            - {name: author, label: Author, widget: string, default: Maeve Finnegan}
            - {name: title, label: Title}
            - {name: tags, label: Tags, widget: list, fields: [{label: tag, name: Tag, widget: string}]}
            - {name: intro, label: Introduction, widget: string}
            - {name: mainImage, label: Main Image, widget: image, default: /src/images/mitso-default.png}
            - {name: body, label: Body, widget: markdown}
    -
        name: servicesGroup
        label: Services
        folder: src/pages/what-we-offer
        create: true
        fields:
            - {name: category, label: Category, widget: hidden, default: Services}
            - {name: icon, label: Icon, widget: hidden, default: 6}
            - {name: date, label: Date, widget: date}
            - {name: title, label: Title}
            - {name: intro, label: Intro, widget: text}
            - {name: statement, label: Statement, widget: text}
            - {name: listOfServices, label: Services, widget: list, fields: [{label: service, name: Service, widget: string}]}
