backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: assets
collections:
  - name: projects
    label: Projects
    folder: src/pages/case-studies
    create: true
    fields:
      - { name: category, label: Category, default: Case Study, widget: hidden }
      - { 
        name: seo, 
        label: SEO, 
        widget: object,
        fields: [
          { label: SEO Title, name: seoTitle, widget: string, required: false},
          { label: SEO Description, name: seoDescription, widget: text, required: false},
          { label: SEO Image, name: seoImage, widget: image, required: false},
          ]
        }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: intro, label: Introduction, widget: text }
      - {
          name: mainImage,
          label: Main Image,
          widget: image,
          default: /src/images/mitso-default.png,
        }
      - { name: body, label: Body, widget: markdown }
      - {
          name: imageBlock,
          label: Image Block,
          widget: list,
          fields: [{ label: image, name: Image, widget: image }],
        }
      - { name: testimonial, label: Testimonial, widget: text }
  - name: posts
    label: Posts
    folder: src/pages/thoughts
    create: true
    fields:
      - { name: category, label: Category, default: Blog, widget: hidden }
      - { 
        name: seo, 
        label: SEO, 
        widget: object,
        fields: [
          { label: SEO Title, name: seoTitle, widget: string, required: false},
          { label: SEO Description, name: seoDescription, widget: text, required: false},
          { label: SEO Image, name: seoImage, widget: image, required: false},
          ]
        }
      - { name: date, label: Date, widget: date }
      - { name: author, label: Author, widget: string, default: Maeve Finnegan }
      - { name: title, label: Title }
      - {
          name: tags,
          label: Tags,
          widget: list,
          fields: [{ label: tag, name: Tag, widget: string }],
        }
      - { name: intro, label: Introduction, widget: string }
      - {
          name: mainImage,
          label: Main Image,
          widget: image,
          default: /src/images/mitso-default.png,
        }
      - { name: body, label: Body, widget: markdown }
  - name: homepage
    label: Homepage
    files: 
      - label: Content
        name: content
        file: site/content/homepage.md
        fields:
          - { name: category, label: Category, widget: hidden, default: noPage }
          - { 
            name: seo, 
            label: SEO, 
            widget: object,
            fields: [
              { label: SEO Title, name: seoTitle, widget: string, required: false},
              { label: SEO Description, name: seoDescription, widget: text, required: false},
              { label: SEO Image, name: seoImage, widget: image, required: false},
              ]
            }
          - {label: Title, name: title, widget: string}
          - {label: Plan, name: plan, widget: text}
          - {label: Brand, name: brand, widget: text}
          - {label: Promote, name: promote, widget: text}
          - {label: Review, name: review, widget: text}
  - name: whoWeAre
    label: Who We Are
    files: 
      - label: Content
        name: content
        file: site/content/whoWeAre.md
        fields:
          - { name: category, label: Category, widget: hidden, default: noPage }
          - { name: text01, label: Text 01, widget: text }
          - { name: text02, label: Text 02, widget: text }
          - { 
            name: seo, 
            label: SEO, 
            widget: object,
            fields: [
              { label: SEO Title, name: seoTitle, widget: string, required: false},
              { label: SEO Description, name: seoDescription, widget: text, required: false},
              { label: SEO Image, name: seoImage, widget: image, required: false},
              ]
            }
          - {label: Title, name: title, widget: string}
  - name: howWeWork
    label: How We Work
    files: 
      - label: Content
        name: content
        file: site/content/howWeWork.md
        fields:
          - { name: category, label: Category, widget: hidden, default: noPage }
          - {label: Slide 01 Title, name: slide01title, widget: string}
          - {label: Slide 01 Text, name: slide01text, widget: string}
          - {label: Slide 02 Title, name: slide02title, widget: string}
          - {label: Slide 02 Text, name: slide02text, widget: string}
          - {label: Slide 03 Title, name: slide03title, widget: string}
          - {label: Slide 03 Text, name: slide03text, widget: string}
          - {label: Slide 04 Title, name: slide04title, widget: string}
          - {label: Slide 04 Text, name: slide04text, widget: string}
  - name: thoughts
    label: Thoughts
    files: 
      - label: Content
        name: content
        file: site/content/thoughts.md
        fields:
          - { name: category, label: Category, widget: hidden, default: noPage }
          - { 
            name: seo, 
            label: SEO, 
            widget: object,
            fields: [
              { label: SEO Title, name: seoTitle, widget: string, required: false},
              { label: SEO Description, name: seoDescription, widget: text, required: false},
              { label: SEO Image, name: seoImage, widget: image, required: false},
              ]
            }
          - {label: Intro, name: intro, widget: string}
  - name: caseStudies
    label: Case Studies
    files: 
      - label: Content
        name: content
        file: site/content/caseStudies.md
        fields:
          - { name: category, label: Category, widget: hidden, default: noPage }
          - { 
            name: seo, 
            label: SEO, 
            widget: object,
            fields: [
              { label: SEO Title, name: seoTitle, widget: string, required: false},
              { label: SEO Description, name: seoDescription, widget: text, required: false},
              { label: SEO Image, name: seoImage, widget: image, required: false},
              ]
            }
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text}
          - {label: others, name: others, widget: text}
  - name: servicesGroup
    label: Services
    folder: src/pages/what-we-offer
    create: true
    fields:
      - { name: category, label: Category, widget: hidden, default: Services }
      - { 
        name: seo, 
        label: SEO, 
        widget: object,
        fields: [
          { label: SEO Title, name: seoTitle, widget: string, required: false},
          { label: SEO Description, name: seoDescription, widget: text, required: false},
          { label: SEO Image, name: seoImage, widget: image, required: false},
          ]
        }
      - { name: icon, label: Icon, widget: hidden, default: 6 }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: intro, label: Intro, widget: text }
      - { name: text01, label: Text 01, widget: text }
      - { name: text02, label: Text 02, widget: text }
      - {
          name: statementImage,
          label: Statement Image,
          widget: image,
          default: /src/images/mitso-default.png,
        }
      - { name: statement, label: Statement, widget: text }
      - { name: serviceText, label: Service Text, widget: text }
      - {
          name: listOfServices,
          label: Services,
          widget: list,
          fields: [{ label: service, name: Service, widget: string }],
        }
  - name: teamMembers
    label: Team Members
    files: 
      - label: Content
        name: content
        file: site/content/team.md
        fields:
          - { name: category, label: Category, default: noPage, widget: hidden }
          - {label: Title, name: title, widget: string}
          - {
            name: teamMember,
            label: Team Member,
            widget: list,
            fields: [
              { label: Image, name: img, widget: image },
              { label: Image on Hover, name: imgSwap, widget: image },
              { label: Name, name: name, widget: string },
              { label: What, name: what, widget: string },
              { label: Where, name: where, widget: string },
              { label: When, name: when, widget: string },
              { label: Why, name: why, widget: string },
              { label: Psst, name: psst, widget: string },
              { label: LinkedIn, name: linkedin, widget: string },
            ],
          }
  - name: workWithMitso
    label: Work with MiTSO
    files: 
      - label: Content
        name: content
        file: site/content/workWithMitso.md
        fields:
          - { name: category, label: Category, widget: hidden, default: noPage }
          - { 
            name: seo, 
            label: SEO, 
            widget: object,
            fields: [
              { label: SEO Title, name: seoTitle, widget: string, required: false},
              { label: SEO Description, name: seoDescription, widget: text, required: false},
              { label: SEO Image, name: seoImage, widget: image, required: false},
              ]
            }
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text}
  - name: takeOff
    label: Takeoff
    files: 
      - label: Content
        name: content
        file: site/content/takeOff.md
        fields:
          - { name: category, label: Category, widget: hidden, default: noPage }
          - { name: title, label: Title, widget: string }
          - { name: youtube, label: Youtube ID, widget: string }
          - { name: text01, label: Text 01, widget: text }
          - { name: text02, label: Text 02, widget: text }
          - { 
            name: seo, 
            label: SEO, 
            widget: object,
            fields: [
              { label: SEO Title, name: seoTitle, widget: string, required: false},
              { label: SEO Description, name: seoDescription, widget: text, required: false},
              { label: SEO Image, name: seoImage, widget: image, required: false},
              ]
            }
  - name: socialMedia
    label: Social Media
    files: 
      - label: Content
        name: content
        file: site/content/socialMedia.md
        fields:
          - { name: facebook, label: Facebook, widget: string }
          - { name: twitter, label: Twitter, widget: string }
          - { name: linkedin, label: LinkedIn, widget: string }
